# Generated by Django 3.0.6 on 2020-05-21 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='asintomatico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='condicion',
            field=models.CharField(choices=[('A', 'Asintomático'), ('S', 'Sintomático'), ('F', 'Fallecido'), ('EE', 'En espera'), ('A', 'Aislado')], default='A', help_text='Sintomático o asintomático', max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_defuncion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='patologias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('E', 'Enfermo'), ('C', 'Curado'), ('F', 'Fallecido'), ('EE', 'En espera'), ('A', 'Aislado')], default='N', help_text='Estado en que se encuentra el paciente', max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('max_pacientes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='app.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitales', to='app.Provincia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='app.Hospital'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='app.Medico'),
        ),
    ]
