# Generated by Django 3.0.6 on 2020-05-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200521_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'hospitales'},
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.IntegerField(help_text='Solo números', unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='condicion',
            field=models.CharField(choices=[('A', 'Asintomático'), ('S', 'Sintomático')], default='A', help_text='Sintomático o asintomático', max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(help_text='Solo números', unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('A', 'Aislado'), ('C', 'Curado'), ('E', 'Enfermo'), ('EE', 'En espera'), ('F', 'Fallecido')], default='N', help_text='Estado en que se encuentra el paciente', max_length=2),
        ),
    ]
