# Generated by Django 3.0.6 on 2020-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200521_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.BooleanField(help_text='Si hay disponibilidad o no del recurso')),
                ('cantidad', models.IntegerField(help_text='Stock disponible del recurso')),
            ],
        ),
    ]
