# Generated by Django 3.0.6 on 2020-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200521_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
