# Generated by Django 3.0.6 on 2020-05-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app', '0007_solicitudrecurso'), ('app', '0008_auto_20200528_1923'), ('app', '0009_auto_20200528_1933'), ('app', '0010_auto_20200528_2023')]

    dependencies = [
        ('app', '0006_auto_20200528_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobada'), ('P', 'Pendiente'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudRecursoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad solicitada')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recurso')),
                ('solicitudrecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SolicitudRecurso')),
            ],
        ),
        migrations.AddField(
            model_name='solicitudrecurso',
            name='recursos',
            field=models.ManyToManyField(related_name='solicitudes', through='app.SolicitudRecursoItem', to='app.Recurso'),
        ),
        migrations.AlterField(
            model_name='solicitudrecurso',
            name='motivo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
