# Generated by Django 3.0.6 on 2020-05-28 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_solicitudrecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecurso',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.Hospital'),
            preserve_default=False,
        ),
    ]
