# Generated by Django 3.0.6 on 2020-05-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_solicitudrecurso_squashed_0010_auto_20200528_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecurso',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.Hospital'),
        ),
    ]
