# Generated by Django 3.0.7 on 2020-06-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200528_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='direccion',
            field=models.CharField(blank=True, help_text='Direccion donde reside del Paciente', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='localidad',
            field=models.CharField(blank=True, default='Resistencia', help_text='Localidad donde reside del Paciente', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Direccion donde reside del Paciente', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(blank=True, default='Resistencia', help_text='Localidad donde reside del Paciente', max_length=200, null=True),
        ),
    ]
