# Generated by Django 3.0.6 on 2020-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200528_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudrecursoitem',
            old_name='solicitudRecurso',
            new_name='solicitudrecurso',
        ),
        migrations.AlterField(
            model_name='solicitudrecurso',
            name='motivo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
