# Generated by Django 3.0.7 on 2020-06-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200620_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de confirmación del caso como COVID-19 positivo', null=True),
        ),
    ]
