# Generated by Django 3.0.7 on 2020-06-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20200622_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecurso',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudrecursoitem',
            name='cantidad_enviada',
            field=models.IntegerField(default=1, help_text='Cantidad enviada'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='direccion',
            field=models.CharField(blank=True, help_text='Direccion donde reside', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='localidad',
            field=models.CharField(blank=True, default='Resistencia', help_text='Localidad donde reside', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Direccion donde reside', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(blank=True, default='Resistencia', help_text='Localidad donde reside', max_length=200, null=True),
        ),
    ]
